name: GroundMCCustomRecipes
version: ${env.GIT_COMMIT}
author: GiantTreeLP
main: gtlp.groundmc.customrecipes.CustomRecipes
depends: [GroundMCKotlinLoader]

commands:
  customrecipes:
    description: CustomRecipes
    permission: customrecipes.admin
    usage: /<command>

permissions:
  customrecipes.*:
    description: Gives access to all functionality in this plugin.
    children:
      customrecipes.admin: true
  customrecipes.admin:
    description: Gives access to all functionality in this plugin.
    default: op
    children:
      customrecipes.replant_crops: true
      customrecipes.disenchant: true
  customrecipes.replant_crops:
    description: Allows a player to replant crops by right-clicking with a hoe.
  customrecipes.disenchant:
    description: Allows a player to disenchant an enchanted Item and get an enchanted book with the enchantment on it.
